# Generated by Django 5.1.4 on 2026-10-08 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_at', models.DateTimeField(auto_now_add=True, verbose_name='iniciada el')),
                ('terminada_at', models.DateTimeField(blank=True, null=True, verbose_name='terminada el')),
                ('crear', models.BooleanField(default=False, verbose_name='crear nuevos')),
                ('actualizar', models.BooleanField(default=False, verbose_name='actualizar información')),
                ('desactivar', models.BooleanField(default=False, verbose_name='desactivar bajas')),
                ('simulacion', models.BooleanField(default=False, help_text='Se calculó lo que cambiaría, sin guardar nada.', verbose_name='vista previa')),
                ('estado', models.CharField(choices=[('ok', 'Correcta'), ('error', 'Con error')], default='ok', max_length=10, verbose_name='estado')),
                ('resumen', models.JSONField(blank=True, default=dict, verbose_name='resumen')),
                ('excepciones', models.JSONField(blank=True, default=list, verbose_name='excepciones')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('ejecutada_por', models.ForeignKey(blank=True, help_text='Vacío cuando la corre el comando programado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_odoo', to=settings.AUTH_USER_MODEL, verbose_name='ejecutada por')),
            ],
            options={
                'verbose_name': 'sincronización con Odoo',
                'verbose_name_plural': 'sincronizaciones con Odoo',
                'ordering': ('-iniciada_at',),
            },
        ),
    ]
