# Generated by Django 5.1.4 on 2026-10-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sincronizacion',
            name='eliminar',
            field=models.BooleanField(default=False, verbose_name='eliminar a quien no está en Odoo'),
        ),
    ]
