# Generated by Django 5.1.4 on 2026-09-29 16:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_pais_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('titulo', models.CharField(max_length=200, verbose_name='nombre del reto')),
                ('descripcion', models.TextField(verbose_name='descripción / instrucciones')),
                ('categoria', models.CharField(choices=[('cultura', 'Cultura'), ('ritmo', 'Ritmo Supli'), ('infraestructura', 'Infraestructura tecnológica'), ('kms', 'KMS'), ('aprende', 'Supli aprende'), ('impulsa', 'Supli impulsa')], max_length=20, verbose_name='categoría')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Abierto'), ('cerrado', 'Cerrado'), ('finalizado', 'Finalizado')], default='borrador', max_length=20, verbose_name='estado')),
                ('cuenta_para_desempeno', models.BooleanField(default=False, help_text='Los retos de cultura no cuentan para el Performance.', verbose_name='cuenta para desempeño')),
                ('alcance', models.CharField(choices=[('todos', 'Toda la empresa'), ('areas', 'Por área'), ('personas', 'Personas puntuales')], default='todos', max_length=20, verbose_name='público objetivo')),
                ('pais', models.CharField(blank=True, help_text='Vacío = sin filtrar por país.', max_length=80, verbose_name='país')),
                ('cierra_el', models.DateField(verbose_name='cierra el')),
                ('formatos_evidencia', models.JSONField(default=list, help_text='texto, imagen, pdf, enlace.', verbose_name='formatos de evidencia')),
                ('visibilidad_evidencia', models.CharField(choices=[('lider_people', 'Solo el líder responsable y People'), ('participantes', 'Líder, People y participantes del reto'), ('organizacion', 'Toda la organización')], default='lider_people', max_length=20, verbose_name='visibilidad de la evidencia')),
                ('publicado_en', models.DateTimeField(blank=True, null=True, verbose_name='publicado el')),
                ('cerrado_en', models.DateTimeField(blank=True, null=True, verbose_name='cerrado el')),
                ('finalizado_en', models.DateTimeField(blank=True, null=True, verbose_name='finalizado el')),
                ('areas', models.ManyToManyField(blank=True, related_name='retos', to='accounts.area', verbose_name='áreas')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('personas', models.ManyToManyField(blank=True, related_name='retos_invitado', to=settings.AUTH_USER_MODEL, verbose_name='personas')),
            ],
            options={
                'verbose_name': 'reto',
                'verbose_name_plural': 'retos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('formato', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('pdf', 'PDF'), ('enlace', 'Enlace (incluye video)')], max_length=20, verbose_name='formato de la evidencia')),
                ('entrega_texto', models.TextField(blank=True, verbose_name='evidencia en texto')),
                ('entrega_link', models.URLField(blank=True, max_length=500, verbose_name='enlace de la evidencia')),
                ('estado', models.CharField(choices=[('entregada', 'Entregada'), ('valorada', 'Valorada'), ('descalificada', 'No cumple')], default='entregada', max_length=20, verbose_name='estado')),
                ('puntaje_final', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='puntaje final')),
                ('puntaje_desempate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='puntaje del desempate')),
                ('bonus', models.PositiveSmallIntegerField(default=0, verbose_name='bonus por desempate')),
                ('es_ganador', models.BooleanField(default=False, verbose_name='ganador del reto')),
                ('motivo_descalificacion', models.TextField(blank=True, verbose_name='motivo de la descalificación')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_challenge', to=settings.AUTH_USER_MODEL, verbose_name='participante')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='challenge.reto', verbose_name='reto')),
            ],
            options={
                'verbose_name': 'participación',
                'verbose_name_plural': 'participaciones',
                'ordering': ('-created_at',),
                'unique_together': {('reto', 'participante')},
            },
        ),
        migrations.CreateModel(
            name='CriterioReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('nombre', models.CharField(max_length=120, verbose_name='criterio')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('desempate', models.BooleanField(default=False, help_text='Los tres criterios con los que se rompe un empate.', verbose_name='entra en el desempate')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='challenge.reto', verbose_name='reto')),
            ],
            options={
                'verbose_name': 'criterio del reto',
                'verbose_name_plural': 'criterios del reto',
                'ordering': ('orden', 'id'),
                'unique_together': {('reto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='CambioReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('descripcion', models.TextField(verbose_name='qué cambió')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_retos', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='challenge.reto', verbose_name='reto')),
            ],
            options={
                'verbose_name': 'cambio del reto',
                'verbose_name_plural': 'cambios del reto',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SolicitudRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida')], default='pendiente', max_length=20, verbose_name='estado')),
                ('respuesta', models.TextField(blank=True, verbose_name='respuesta')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='atendida por')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='challenge.participacion', verbose_name='participación')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones_challenge', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
            ],
            options={
                'verbose_name': 'solicitud de revisión',
                'verbose_name_plural': 'solicitudes de revisión',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('es_jurado', models.BooleanField(default=False, verbose_name='es el jurado del reto')),
                ('comentario', models.TextField(blank=True, verbose_name='comentario para el colaborador')),
                ('no_cumple', models.BooleanField(default=False, verbose_name='la evidencia no cumple')),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='puntaje (0–100)')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_challenge', to=settings.AUTH_USER_MODEL, verbose_name='evaluador')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='challenge.participacion', verbose_name='participación')),
            ],
            options={
                'verbose_name': 'valoración',
                'verbose_name_plural': 'valoraciones',
                'ordering': ('created_at',),
                'unique_together': {('participacion', 'evaluador')},
            },
        ),
        migrations.CreateModel(
            name='JuradoReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados_challenge', to=settings.AUTH_USER_MODEL, verbose_name='jurado')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='challenge.reto', verbose_name='reto')),
            ],
            options={
                'verbose_name': 'jurado del reto',
                'verbose_name_plural': 'jurados del reto',
                'unique_together': {('reto', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='PuntajeCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('nivel', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='nivel')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='challenge.criterioreto', verbose_name='criterio')),
                ('valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntajes', to='challenge.valoracion', verbose_name='valoración')),
            ],
            options={
                'verbose_name': 'puntaje por criterio',
                'verbose_name_plural': 'puntajes por criterio',
                'unique_together': {('valoracion', 'criterio')},
            },
        ),
    ]
