# Generated by Django 5.1.4 on 2026-09-09 22:19

import apps.accounts.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('base_path', models.CharField(help_text='Ej: /ventas', max_length=100, verbose_name='ruta base')),
                ('icon', models.CharField(blank=True, help_text='Nombre en lucide-react', max_length=50, verbose_name='ícono')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'aplicación',
                'verbose_name_plural': 'aplicaciones',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.application', verbose_name='aplicación')),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'ordering': ('application__order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('code', models.SlugField(unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo corporativo')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='usuario')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='apellidos')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='área')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('kind', models.CharField(choices=[('admin', 'Admin'), ('lider', 'Líder'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20, verbose_name='tipo de usuario')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al admin de Django')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='último ingreso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='jefe directo')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('applications', models.ManyToManyField(blank=True, help_text='Apps a las que entra directamente, además de las que le den sus roles.', related_name='users', to='accounts.application', verbose_name='aplicaciones')),
                ('extra_permissions', models.ManyToManyField(blank=True, help_text='Permisos sueltos que se suman a los de sus roles.', related_name='users', to='accounts.permission', verbose_name='permisos adicionales')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='accounts.role', verbose_name='roles')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('first_name', 'last_name'),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
