# Generated by Django 5.1.4 on 2026-09-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_area_como_entidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accent',
            field=models.CharField(choices=[('neutral', 'Neutro'), ('indigo', 'Índigo'), ('blue', 'Azul'), ('emerald', 'Verde'), ('amber', 'Ámbar'), ('rose', 'Rosa'), ('violet', 'Violeta')], default='neutral', max_length=20, verbose_name='color de acento'),
        ),
        migrations.AddField(
            model_name='user',
            name='radius',
            field=models.CharField(choices=[('sharp', 'Recto'), ('default', 'Normal'), ('rounded', 'Redondeado')], default='default', max_length=10, verbose_name='redondeado'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('system', 'Sistema')], default='system', max_length=10, verbose_name='tema'),
        ),
    ]
