# Generated by Django 5.1.4 on 2026-09-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_preferencias_de_apariencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Si se llena, esta app es un sub-módulo y cuelga de la otra en el menú.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.application', verbose_name='contenedor'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizacion',
            field=models.CharField(blank=True, max_length=120, verbose_name='organización'),
        ),
        migrations.AddField(
            model_name='user',
            name='punto_venta',
            field=models.CharField(blank=True, help_text='Solo aplica para asesores y promotores.', max_length=120, verbose_name='CAV / punto de venta'),
        ),
        migrations.AddField(
            model_name='user',
            name='regional',
            field=models.CharField(blank=True, max_length=120, verbose_name='regional'),
        ),
    ]
