# Generated by Django 5.1.4 on 2026-09-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organigrama_y_submodulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(blank=True, help_text='Colombia, Perú… Lo mantiene Odoo cuando entre la integración.', max_length=80, verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Vacío solo para quien no tiene cuenta corporativa (asesores y promotores).', max_length=254, null=True, unique=True, verbose_name='correo corporativo'),
        ),
    ]
