# Generated by Django 5.1.4 on 2026-09-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bordes_rectos_por_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_instalada',
            field=models.BooleanField(default=False, verbose_name='instaló la app'),
        ),
        migrations.AddField(
            model_name='user',
            name='inicios_para_aviso_app',
            field=models.PositiveSmallIntegerField(default=0, help_text='En 0 se le ofrece instalar la app al entrar.', verbose_name='inicios de sesión para volver a ofrecer la app'),
        ),
    ]
