# Generated by Django 5.1.4 on 2026-10-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_app_instalable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(blank=True, max_length=30, verbose_name='cédula'),
        ),
        migrations.AddField(
            model_name='user',
            name='odoo_id',
            field=models.PositiveIntegerField(blank=True, help_text='Vacío para quien no viene de Odoo (cuentas de servicio, admin).', null=True, unique=True, verbose_name='id en Odoo'),
        ),
        migrations.AddField(
            model_name='user',
            name='sincronizado_odoo_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última sincronización con Odoo'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('odoo_id', models.PositiveIntegerField(unique=True, verbose_name='id en Odoo')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='accounts.departamento', verbose_name='departamento padre')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='accounts.departamento', verbose_name='departamento'),
        ),
    ]
