# Generated by Django 5.1.4 on 2026-10-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_odoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='odoo',
            field=models.BooleanField(default=False, help_text='La marca la sincronización. Las áreas solo se crean y cambian desde Odoo.', verbose_name='viene de Odoo'),
        ),
    ]
