# Generated by Django 5.1.4 on 2026-09-10 05:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_producto', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='código del producto')),
                ('nombre_producto', models.CharField(max_length=60, verbose_name='nombre del producto')),
                ('marca', models.CharField(max_length=60, verbose_name='marca')),
                ('precio_venta_claro', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='precio de venta Claro')),
                ('precio_venta_coltrade', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='precio de venta Coltrade')),
                ('puntaje', models.IntegerField(blank=True, null=True, verbose_name='puntaje')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'bi_trade_productos',
                'ordering': ('nombre_producto',),
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_punto_venta', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='código del punto de venta')),
                ('nombre_pdv', models.CharField(max_length=100, verbose_name='nombre del punto de venta')),
                ('regional', models.CharField(blank=True, choices=[('Zona Sur', 'Zona Sur'), ('Zona Norte', 'Zona Norte'), ('Plaza Claro', 'Plaza Claro'), ('Nacional', 'Nacional')], max_length=100, null=True, verbose_name='regional')),
                ('materiales', models.CharField(blank=True, choices=[('Todos los materiales', 'Todos los materiales'), ('Sin todos los materiales', 'Sin todos los materiales')], max_length=100, null=True, verbose_name='materiales')),
            ],
            options={
                'verbose_name': 'punto de venta',
                'verbose_name_plural': 'puntos de venta',
                'db_table': 'bi_trade_puntos_venta',
                'ordering': ('nombre_pdv',),
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_venta', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la venta')),
                ('fecha_venta', models.DateField(verbose_name='fecha de la venta')),
                ('cantidad_vendida', models.PositiveIntegerField(verbose_name='cantidad vendida')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='bi_trade.producto', verbose_name='producto')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='bi_trade.puntoventa', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'bi_trade_ventas',
                'ordering': ('-fecha_venta', '-id_venta'),
            },
        ),
    ]
