# Generated by Django 5.1.4 on 2026-09-10 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_inventario', models.AutoField(primary_key=True, serialize=False, verbose_name='id de inventario')),
                ('cantidad_inventario', models.PositiveIntegerField(verbose_name='cantidad en inventario')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='bi_trade.producto', verbose_name='producto')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='bi_trade.puntoventa', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
                'db_table': 'bi_trade_inventario',
                'ordering': ('id_punto_venta__nombre_pdv', 'id_producto__nombre_producto'),
                'unique_together': {('id_producto', 'id_punto_venta')},
            },
        ),
        migrations.CreateModel(
            name='MetaComercial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_meta', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la meta')),
                ('meta_cantidad', models.PositiveIntegerField(verbose_name='meta de unidades')),
                ('meta_dinero', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='meta de dinero')),
                ('meta_puntos', models.PositiveIntegerField(verbose_name='meta de puntos')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='bi_trade.producto', verbose_name='producto')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta', on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='bi_trade.puntoventa', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
                'db_table': 'bi_trade_metas',
                'ordering': ('id_punto_venta__nombre_pdv', 'id_producto__nombre_producto'),
                'unique_together': {('id_producto', 'id_punto_venta')},
            },
        ),
    ]
