# Generated by Django 5.1.4 on 2026-09-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0003_meta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metacomercial',
            name='meta_dinero',
        ),
        migrations.RemoveField(
            model_name='metacomercial',
            name='meta_puntos',
        ),
    ]
