# Generated by Django 5.1.4 on 2026-09-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0004_remove_metacomercial_meta_dinero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_campana', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la campaña')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('desde', models.DateField(verbose_name='vigente desde')),
                ('hasta', models.DateField(verbose_name='vigente hasta')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('ventas_minimas', models.PositiveIntegerField(default=120, help_text='Unidades vendidas en toda la campaña para poder participar.', verbose_name='ventas totales mínimas')),
                ('tickets_minimos', models.PositiveIntegerField(default=3, help_text='Tickets acumulados para entrar al sorteo.', verbose_name='tickets mínimos')),
                ('foco_minimo', models.PositiveIntegerField(default=5, help_text='Unidades de producto foco en un día para duplicar los tickets. 0 lo apaga.', verbose_name='mínimo de productos foco al día')),
                ('bono_ventas', models.PositiveIntegerField(default=20, verbose_name='ventas del día para el bono')),
                ('bono_cargadores', models.PositiveIntegerField(default=5, verbose_name='cargadores del día para el bono')),
                ('bono_tickets', models.PositiveIntegerField(default=3, help_text='Se suman a los de la escala, no la reemplazan. 0 lo apaga.', verbose_name='tickets del bono')),
                ('productos_cargador', models.ManyToManyField(blank=True, related_name='campanas_cargador', to='bi_trade.producto', verbose_name='productos que cuentan como cargador')),
                ('productos_foco', models.ManyToManyField(blank=True, related_name='campanas_foco', to='bi_trade.producto', verbose_name='productos que dan doble ticket')),
            ],
            options={
                'verbose_name': 'campaña',
                'verbose_name_plural': 'campañas',
                'db_table': 'bi_trade_campanas',
                'ordering': ('-desde', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Acelerador',
            fields=[
                ('id_acelerador', models.AutoField(primary_key=True, serialize=False, verbose_name='id del acelerador')),
                ('ventas_totales', models.PositiveIntegerField(verbose_name='ventas totales de la campaña')),
                ('tickets_por_dia', models.PositiveIntegerField(verbose_name='tickets extra por día cumplido')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceleradores', to='bi_trade.campana', verbose_name='campaña')),
            ],
            options={
                'verbose_name': 'acelerador',
                'verbose_name_plural': 'aceleradores',
                'db_table': 'bi_trade_aceleradores',
                'ordering': ('campana', 'ventas_totales'),
                'unique_together': {('campana', 'ventas_totales')},
            },
        ),
        migrations.CreateModel(
            name='EscalaTicket',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la escala')),
                ('ventas', models.PositiveIntegerField(verbose_name='ventas del día')),
                ('tickets', models.PositiveIntegerField(verbose_name='tickets que otorga')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='bi_trade.campana', verbose_name='campaña')),
            ],
            options={
                'verbose_name': 'escala de tickets',
                'verbose_name_plural': 'escalas de tickets',
                'db_table': 'bi_trade_escalas_ticket',
                'ordering': ('campana', 'ventas'),
                'unique_together': {('campana', 'ventas')},
            },
        ),
    ]
