# Generated by Django 5.1.4 on 2026-09-11 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0005_campana_acelerador_escalaticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlacePublico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_enlace', models.AutoField(primary_key=True, serialize=False, verbose_name='id del enlace')),
                ('nombre', models.CharField(help_text='Para quién es: «Gerencia Claro», «Regional Norte».', max_length=120, verbose_name='nombre')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='token de la URL')),
                ('clave_hash', models.CharField(max_length=128, verbose_name='hash de la contraseña')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión de la contraseña')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('expira', models.DateTimeField(blank=True, null=True, verbose_name='expira')),
                ('accesos', models.PositiveIntegerField(default=0, verbose_name='accesos')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='último acceso')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlaces_bi_trade', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'enlace público',
                'verbose_name_plural': 'enlaces públicos',
                'db_table': 'bi_trade_enlaces_publicos',
                'ordering': ('-created_at',),
            },
        ),
    ]
