# Generated by Django 5.1.4 on 2026-09-11 04:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0007_productohc_puntoventahc_enlacepublico_canal_ventahc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFalabella',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_producto', models.CharField(db_column='id_producto_falabella', max_length=60, primary_key=True, serialize=False, verbose_name='código del producto')),
                ('nombre_producto', models.CharField(max_length=60, verbose_name='nombre del producto')),
                ('marca', models.CharField(max_length=60, verbose_name='marca')),
                ('precio_venta_falabella', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='precio de venta Falabella')),
                ('precio_venta_coltrade', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='precio de venta Coltrade')),
                ('puntaje', models.IntegerField(blank=True, null=True, verbose_name='puntaje')),
            ],
            options={
                'verbose_name': 'producto Falabella',
                'verbose_name_plural': 'productos Falabella',
                'db_table': 'bi_trade_productos_falabella',
                'ordering': ('nombre_producto',),
            },
        ),
        migrations.CreateModel(
            name='PuntoVentaFalabella',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_punto_venta', models.CharField(db_column='id_punto_venta_falabella', max_length=60, primary_key=True, serialize=False, verbose_name='código del punto de venta')),
                ('nombre_pdv', models.CharField(max_length=100, verbose_name='nombre del punto de venta')),
                ('regional', models.CharField(blank=True, choices=[('Zona Norte', 'Zona Norte'), ('Zona Centro', 'Zona Centro'), ('Zona Sur', 'Zona Sur'), ('Nacional', 'Nacional')], max_length=100, null=True, verbose_name='regional')),
                ('materiales', models.CharField(blank=True, choices=[('Todos los materiales', 'Todos los materiales'), ('Sin todos los materiales', 'Sin todos los materiales')], max_length=100, null=True, verbose_name='materiales')),
            ],
            options={
                'verbose_name': 'punto de venta Falabella',
                'verbose_name_plural': 'puntos de venta Falabella',
                'db_table': 'bi_trade_puntos_venta_falabella',
                'ordering': ('nombre_pdv',),
            },
        ),
        migrations.AlterField(
            model_name='enlacepublico',
            name='canal',
            field=models.CharField(choices=[('claro', 'Claro'), ('hc', 'Homecenter'), ('falabella', 'Falabella')], default='claro', max_length=10, verbose_name='canal'),
        ),
        migrations.CreateModel(
            name='VentaFalabella',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_venta', models.AutoField(db_column='id_venta_falabella', primary_key=True, serialize=False, verbose_name='id de la venta')),
                ('fecha_venta', models.DateField(verbose_name='fecha de la venta')),
                ('cantidad_vendida', models.PositiveIntegerField(verbose_name='cantidad vendida')),
                ('id_producto', models.ForeignKey(db_column='id_producto_falabella', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='bi_trade.productofalabella', verbose_name='producto')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta_falabella', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='bi_trade.puntoventafalabella', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'venta Falabella',
                'verbose_name_plural': 'ventas Falabella',
                'db_table': 'bi_trade_ventas_falabella',
                'ordering': ('-fecha_venta', '-id_venta'),
            },
        ),
        migrations.CreateModel(
            name='MetaComercialFalabella',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_meta', models.AutoField(db_column='id_meta_falabella', primary_key=True, serialize=False, verbose_name='id de la meta')),
                ('fecha_meta', models.DateField(verbose_name='fecha de la meta')),
                ('meta_cantidad', models.PositiveIntegerField(verbose_name='meta de unidades')),
                ('id_producto', models.ForeignKey(db_column='id_producto_falabella', on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='bi_trade.productofalabella', verbose_name='producto')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta_falabella', on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='bi_trade.puntoventafalabella', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'meta Falabella',
                'verbose_name_plural': 'metas Falabella',
                'db_table': 'bi_trade_metas_falabella',
                'ordering': ('-fecha_meta', 'id_punto_venta__nombre_pdv', 'id_producto__nombre_producto'),
                'unique_together': {('id_producto', 'id_punto_venta', 'fecha_meta')},
            },
        ),
        migrations.CreateModel(
            name='InventarioFalabella',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_inventario', models.AutoField(db_column='id_inventario_falabella', primary_key=True, serialize=False, verbose_name='id de inventario')),
                ('cantidad_inventario', models.PositiveIntegerField(verbose_name='cantidad en inventario')),
                ('id_producto', models.ForeignKey(db_column='id_producto_falabella', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='bi_trade.productofalabella', verbose_name='producto')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta_falabella', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='bi_trade.puntoventafalabella', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'inventario Falabella',
                'verbose_name_plural': 'inventarios Falabella',
                'db_table': 'bi_trade_inventario_falabella',
                'ordering': ('id_punto_venta__nombre_pdv', 'id_producto__nombre_producto'),
                'unique_together': {('id_producto', 'id_punto_venta')},
            },
        ),
    ]
