# Generated by Django 5.1.4 on 2026-09-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0009_canal_tmk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productofalabella',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='productohc',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='productotmk',
            name='puntaje',
        ),
    ]
