# Generated by Django 5.1.4 on 2026-09-12 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0010_sin_puntaje_canales_aparte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_producto', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='código del producto')),
                ('nombre_producto', models.CharField(max_length=60, verbose_name='nombre del producto')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario.', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'producto del plan Partners',
                'verbose_name_plural': 'productos del plan Partners',
                'db_table': 'bi_trade_productos_partners',
                'ordering': ('nombre_producto',),
            },
        ),
        migrations.CreateModel(
            name='PuntoVentaPartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_punto_venta', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='código del punto de venta')),
                ('nombre_pdv', models.CharField(max_length=100, verbose_name='nombre del punto de venta')),
                ('regional', models.CharField(choices=[('Región Centro (Z. Norte)', 'Región Centro (Z. Norte)'), ('Región Centro (Z. Sur)', 'Región Centro (Z. Sur)'), ('Región Costa', 'Región Costa')], max_length=60, verbose_name='regional')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario.', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'punto de venta del plan Partners',
                'verbose_name_plural': 'puntos de venta del plan Partners',
                'db_table': 'bi_trade_puntos_venta_partners',
                'ordering': ('nombre_pdv',),
            },
        ),
        migrations.CreateModel(
            name='RegistroPartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_registro', models.AutoField(primary_key=True, serialize=False, verbose_name='id del registro')),
                ('regional', models.CharField(choices=[('Región Centro (Z. Norte)', 'Región Centro (Z. Norte)'), ('Región Centro (Z. Sur)', 'Región Centro (Z. Sur)'), ('Región Costa', 'Región Costa')], max_length=60, verbose_name='regional')),
                ('marca', models.CharField(choices=[('Apple', 'Apple'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Motorola', 'Motorola'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('Tecno', 'Tecno'), ('Vivo', 'Vivo'), ('ZTE', 'ZTE')], max_length=60, verbose_name='marca')),
                ('fecha_recomendacion', models.DateField(verbose_name='fecha de la recomendación')),
                ('serial', models.CharField(max_length=40, verbose_name='número de serial')),
                ('documento_promotor', models.CharField(max_length=20, verbose_name='documento del promotor de marca')),
                ('factura', models.CharField(max_length=40, verbose_name='factura')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='bi_trade.productopartner', verbose_name='producto recomendado')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='bi_trade.puntoventapartner', verbose_name='punto de venta')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_partners', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'registro del plan Partners',
                'verbose_name_plural': 'registros del plan Partners',
                'db_table': 'bi_trade_registros_partners',
                'ordering': ('-fecha_recomendacion', '-id_registro'),
                'indexes': [models.Index(fields=['serial'], name='bi_trade_partners_serial')],
            },
        ),
    ]
