# Generated by Django 5.1.4 on 2026-09-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0013_enlace_publico_del_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepublico',
            name='clave_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='hash de la contraseña'),
        ),
    ]
