# Generated by Django 5.1.4 on 2026-09-12 04:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0014_enlace_sin_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopartner',
            name='precio',
            field=models.PositiveIntegerField(default=0, help_text='Con este precio se valora lo recomendado en el tablero.', validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='precio'),
        ),
        migrations.CreateModel(
            name='MetaPartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_meta', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la meta')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='año')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mes')),
                ('marca', models.CharField(choices=[('Apple', 'Apple'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Motorola', 'Motorola'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('Tecno', 'Tecno'), ('Vivo', 'Vivo'), ('ZTE', 'ZTE')], max_length=60, verbose_name='marca')),
                ('meta_unidades', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='meta de unidades')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta', on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='bi_trade.puntoventapartner', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'meta del plan Partners',
                'verbose_name_plural': 'metas del plan Partners',
                'db_table': 'bi_trade_metas_partners',
                'ordering': ('-anio', '-mes', 'id_punto_venta__nombre_pdv', 'marca'),
                'unique_together': {('anio', 'mes', 'id_punto_venta', 'marca')},
            },
        ),
    ]
