# Generated by Django 5.1.4 on 2026-09-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0015_metas_y_precio_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metapartner',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Motorola', 'Motorola'), ('Oppo', 'Oppo'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('TCL', 'TCL'), ('Tecno', 'Tecno'), ('Vivo', 'Vivo'), ('ZTE', 'ZTE')], max_length=60, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='registropartner',
            name='marca',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Motorola', 'Motorola'), ('Oppo', 'Oppo'), ('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('TCL', 'TCL'), ('Tecno', 'Tecno'), ('Vivo', 'Vivo'), ('ZTE', 'ZTE')], max_length=60, verbose_name='marca'),
        ),
    ]
