# Generated by Django 5.1.4 on 2026-09-21 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0016_marcas_oppo_y_tcl'),
    ]

    operations = [
        migrations.AddField(
            model_name='productohc',
            name='ean',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='EAN'),
        ),
        migrations.AddField(
            model_name='productohc',
            name='sku_coltrade',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='SKU Coltrade'),
        ),
        migrations.AlterField(
            model_name='productohc',
            name='marca',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='productohc',
            name='precio_venta_coltrade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='precio de venta Coltrade'),
        ),
        migrations.AlterField(
            model_name='productohc',
            name='precio_venta_hc',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100000000)], verbose_name='precio de venta Homecenter'),
        ),
    ]
