# Generated by Django 5.1.4 on 2026-09-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0018_producto_hc_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productohc',
            name='categoria',
        ),
        migrations.AddField(
            model_name='puntoventahc',
            name='categoria',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True, verbose_name='categoría'),
        ),
    ]
