# Generated by Django 5.1.4 on 2026-10-05 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0019_categoria_en_punto_venta_hc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBelkin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la categoría')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='nombre')),
                ('activa', models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario.', verbose_name='activa')),
            ],
            options={
                'verbose_name': 'categoría del plan Belkin',
                'verbose_name_plural': 'categorías del plan Belkin',
                'db_table': 'bi_trade_categorias_belkin',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='PuntoVentaBelkin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_punto_venta', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='centro de costos')),
                ('nombre_pdv', models.CharField(max_length=100, verbose_name='nombre del punto de venta')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario.', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'punto de venta del plan Belkin',
                'verbose_name_plural': 'puntos de venta del plan Belkin',
                'db_table': 'bi_trade_puntos_venta_belkin',
                'ordering': ('nombre_pdv',),
            },
        ),
        migrations.CreateModel(
            name='RegionalBelkin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_regional', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la regional')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('activa', models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario.', verbose_name='activa')),
            ],
            options={
                'verbose_name': 'regional del plan Belkin',
                'verbose_name_plural': 'regionales del plan Belkin',
                'db_table': 'bi_trade_regionales_belkin',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ProductoBelkin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_producto', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='código del producto')),
                ('nombre_producto', models.CharField(max_length=120, verbose_name='nombre del producto')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario.', verbose_name='activo')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='bi_trade.categoriabelkin', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto del plan Belkin',
                'verbose_name_plural': 'productos del plan Belkin',
                'db_table': 'bi_trade_productos_belkin',
                'ordering': ('nombre_producto',),
            },
        ),
        migrations.CreateModel(
            name='AsesorApple',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_asesor', models.AutoField(primary_key=True, serialize=False, verbose_name='id del asesor')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre y apellido')),
                ('activo', models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario.', verbose_name='activo')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta', on_delete=django.db.models.deletion.PROTECT, related_name='asesores', to='bi_trade.puntoventabelkin', verbose_name='punto de venta')),
            ],
            options={
                'verbose_name': 'asesor Apple',
                'verbose_name_plural': 'asesores Apple',
                'db_table': 'asesor_apple',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='puntoventabelkin',
            name='id_regional',
            field=models.ForeignKey(db_column='id_regional', on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='bi_trade.regionalbelkin', verbose_name='regional'),
        ),
        migrations.CreateModel(
            name='RegistroBelkin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('id_registro', models.AutoField(primary_key=True, serialize=False, verbose_name='id del registro')),
                ('fecha_recomendacion', models.DateField(verbose_name='fecha de la recomendación')),
                ('observacion', models.TextField(blank=True, default='', verbose_name='observación')),
                ('id_asesor', models.ForeignKey(blank=True, db_column='id_asesor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='bi_trade.asesorapple', verbose_name='asesor Apple')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='bi_trade.productobelkin', verbose_name='producto recomendado')),
                ('id_punto_venta', models.ForeignKey(db_column='id_punto_venta', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='bi_trade.puntoventabelkin', verbose_name='punto de venta')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_belkin', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'registro del plan Belkin',
                'verbose_name_plural': 'registros del plan Belkin',
                'db_table': 'bi_trade_registros_belkin',
                'ordering': ('-fecha_recomendacion', '-id_registro'),
            },
        ),
    ]
