# Generated by Django 5.1.4 on 2026-10-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0020_plan_belkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrobelkin',
            name='enlace',
            field=models.ForeignKey(blank=True, db_column='id_enlace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_belkin', to='bi_trade.enlacepublico', verbose_name='enlace público'),
        ),
        migrations.AlterField(
            model_name='enlacepublico',
            name='canal',
            field=models.CharField(choices=[('claro', 'Claro'), ('hc', 'Homecenter'), ('falabella', 'Falabella'), ('tmk', 'Tmk Ecommerce Claro'), ('partners', 'Plan Partners (formulario)'), ('belkin', 'Plan Recomiéndame Belkin (formulario)')], default='claro', max_length=10, verbose_name='canal'),
        ),
    ]
