# Generated by Django 5.1.4 on 2026-10-08 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0021_enlace_publico_belkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoventabelkin',
            name='categoria',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Categoría 1'), (2, 'Categoría 2'), (3, 'Categoría 3')], help_text='Fija cuántas recomendaciones pide cada bono. Sin categoría no gana bono.', null=True, verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='registrobelkin',
            name='fuente',
            field=models.CharField(choices=[('formulario', 'Formulario'), ('informe', 'Informe de ventas Claro')], db_default='formulario', default='formulario', max_length=20, verbose_name='fuente'),
        ),
        migrations.AlterField(
            model_name='puntoventabelkin',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si se desactiva, deja de aparecer en el formulario y, si es fuera de Coltrade, deja de tomar ventas del informe.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='puntoventabelkin',
            name='id_regional',
            field=models.ForeignKey(blank=True, db_column='id_regional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='bi_trade.regionalbelkin', verbose_name='regional'),
        ),
    ]
