# Generated by Django 5.1.4 on 2026-10-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi_trade', '0022_belkin_categoria_y_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacepublico',
            name='canal',
            field=models.CharField(choices=[('claro', 'Claro'), ('hc', 'Homecenter'), ('falabella', 'Falabella'), ('tmk', 'Tmk Ecommerce Claro'), ('belkin_bi', 'Plan Recomiéndame Belkin (tablero)'), ('partners', 'Plan Partners (formulario)'), ('belkin', 'Plan Recomiéndame Belkin (formulario)')], default='claro', max_length=10, verbose_name='canal'),
        ),
    ]
