# Generated by Django 5.1.4 on 2026-09-12 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('periodo', models.DateField(help_text='Primer día del mes.', verbose_name='periodo')),
                ('objetivo', models.TextField(verbose_name='objetivo')),
                ('kpi', models.TextField(verbose_name='KPI / indicador')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='peso (%)')),
                ('tipo_medicion', models.CharField(choices=[('binario', 'Binario — cumple / no cumple'), ('proporcional', 'Proporcional — logrado ÷ meta'), ('proporcional_inverso', 'Proporcional inverso — menos es mejor'), ('formula', 'Fórmula personalizada')], max_length=30, verbose_name='tipo de medición')),
                ('unidad', models.CharField(blank=True, choices=[('unidades', 'Unidades'), ('peso', '$ (pesos)'), ('porcentaje', '%'), ('dias', 'Días'), ('si_no', 'Sí / No')], max_length=20, verbose_name='unidad')),
                ('meta_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Obligatoria salvo en los objetivos binarios.', max_digits=14, null=True, verbose_name='meta')),
                ('umbral_cumplimiento', models.DecimalField(blank=True, decimal_places=2, help_text='Desde dónde cuenta como cumplido. Alimenta el semáforo.', max_digits=14, null=True, verbose_name='umbral de cumplimiento')),
                ('permite_sobrecumplimiento', models.BooleanField(default=False, verbose_name='permite superar el 100%')),
                ('tope_cumplimiento', models.DecimalField(decimal_places=2, default=100, help_text='Se aplica cuando el objetivo no permite sobrecumplimiento.', max_digits=6, verbose_name='tope de cumplimiento')),
                ('formula', models.TextField(blank=True, help_text='Solo cuando el tipo de medición es «fórmula».', verbose_name='fórmula')),
                ('fuente_datos', models.TextField(blank=True, verbose_name='fuente de los datos')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('congelado', 'Congelado')], default='borrador', max_length=20, verbose_name='estado')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to=settings.AUTH_USER_MODEL, verbose_name='colaborador')),
                ('registrado_por', models.ForeignKey(help_text='El jefe o People: el colaborador nunca define su objetivo.', on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('responsable_resultado', models.ForeignKey(blank=True, help_text='Por defecto el colaborador; para asesores y promotores, su Trade Leader.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='responsable del resultado')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'ordering': ('-periodo', 'colaborador_id', '-peso'),
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('periodo', models.DateField(help_text='Primer día del mes.', unique=True, verbose_name='periodo')),
                ('estado', models.CharField(choices=[('definicion', 'En definición'), ('en_medicion', 'En medición'), ('cerrado', 'Cerrado')], default='definicion', max_length=20, verbose_name='estado')),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True, verbose_name='fecha de apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('abierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_abiertos', to=settings.AUTH_USER_MODEL, verbose_name='abierto por')),
            ],
            options={
                'verbose_name': 'periodo',
                'verbose_name_plural': 'periodos',
                'ordering': ('-periodo',),
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('resultado_ejecutado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='resultado ejecutado')),
                ('porcentaje_cumplimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='% de cumplimiento')),
                ('fecha_carga', models.DateTimeField(blank=True, null=True, verbose_name='fecha de carga')),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='estado de validación')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de validación')),
                ('observacion', models.TextField(blank=True, verbose_name='observación')),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_cargados', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
                ('objetivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='performance.objetivo', verbose_name='objetivo')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validados', to=settings.AUTH_USER_MODEL, verbose_name='validado por')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('tipo', models.CharField(blank=True, choices=[('archivo', 'Archivo'), ('link', 'Enlace'), ('acta', 'Acta'), ('reporte', 'Reporte'), ('proyecto', 'Proyecto'), ('base_datos', 'Base de datos'), ('otro', 'Otro')], max_length=20, verbose_name='tipo')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='nombre')),
                ('link_soporte', models.URLField(blank=True, max_length=500, verbose_name='enlace del soporte')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='performance.resultado', verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'evidencia',
                'verbose_name_plural': 'evidencias',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='objetivo',
            index=models.Index(fields=['colaborador', 'periodo'], name='ix_obj_colab_periodo'),
        ),
    ]
