# Generated by Django 5.1.4 on 2026-09-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_objetivos_y_kpis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='edicion_habilitada',
            field=models.BooleanField(default=False, verbose_name='edición habilitada por excepción'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de la habilitación'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='habilitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_habilitados', to=settings.AUTH_USER_MODEL, verbose_name='habilitada por'),
        ),
        migrations.AddField(
            model_name='periodo',
            name='motivo_habilitacion',
            field=models.TextField(blank=True, verbose_name='motivo de la habilitación'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='tipo_medicion',
            field=models.CharField(choices=[('binario', 'Binario — cumple / no cumple'), ('proporcional', 'Proporcional — logrado ÷ meta'), ('proporcional_inverso', 'Proporcional inverso — menos es mejor'), ('cualitativa', 'Cualitativa — entregables / hitos (2 criterios)'), ('formula', 'Fórmula personalizada')], max_length=30, verbose_name='tipo de medición'),
        ),
    ]
