# Generated by Django 5.1.4 on 2026-09-10 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('code', models.CharField(help_text='Ej: A, B, C', max_length=10, verbose_name='código')),
                ('name', models.CharField(help_text='Ej: CULTURA', max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'competencia',
                'verbose_name_plural': 'competencias',
                'ordering': ('order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('evaluation_type', models.CharField(choices=[('lider', 'Evaluación de liderazgo'), ('operativo', 'Evaluación operativa/táctica'), ('mixta', 'Mixta')], default='mixta', max_length=20, verbose_name='tipo')),
                ('start_date', models.DateTimeField(verbose_name='fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='fecha de cierre')),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('activo', 'Activo'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='programado', max_length=20, verbose_name='estado')),
                ('is_anonymous', models.BooleanField(default=False, help_text='El evaluado no ve quién lo calificó.', verbose_name='anonimato')),
                ('comments_required', models.BooleanField(default=False, verbose_name='comentarios obligatorios')),
                ('manager_weight', models.PositiveSmallIntegerField(default=60, help_text='Solo aplica en evaluaciones de liderazgo.', verbose_name='peso del jefe (%)')),
                ('team_weight', models.PositiveSmallIntegerField(default=40, verbose_name='peso del equipo (%)')),
                ('excluded_questions', models.JSONField(blank=True, default=list, help_text='IDs de preguntas que no se aplican en este ciclo.', verbose_name='preguntas excluidas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_cycles_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'ciclo de evaluación',
                'verbose_name_plural': 'ciclos de evaluación',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('evaluator_role', models.CharField(choices=[('jefe', 'Jefe inmediato'), ('equipo', 'Miembro del equipo'), ('autoevaluacion', 'Autoevaluación')], max_length=20, verbose_name='rol del evaluador')),
                ('evaluation_type', models.CharField(choices=[('lider', 'Evaluación de liderazgo'), ('operativo', 'Evaluación operativa/táctica')], max_length=20, verbose_name='tipo de evaluación')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En progreso'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, help_text='Si se desactiva, no aplica para responder ni consolidar.', verbose_name='activa')),
                ('agreements', models.TextField(blank=True, help_text='Campo libre; no califica.', verbose_name='observaciones y acuerdos')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='primera respuesta')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada el')),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations_received', to=settings.AUTH_USER_MODEL, verbose_name='evaluado')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations_to_do', to=settings.AUTH_USER_MODEL, verbose_name='evaluador')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='valoracion.cycle', verbose_name='ciclo')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
                'ordering': ('cycle', 'evaluatee_id'),
                'unique_together': {('cycle', 'evaluator', 'evaluatee')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('statement', models.TextField(verbose_name='enunciado')),
                ('evaluation_type', models.CharField(choices=[('lider', 'Evaluación de liderazgo'), ('operativo', 'Evaluación operativa/táctica')], max_length=20, verbose_name='tipo de evaluación')),
                ('question_type', models.CharField(choices=[('likert', 'Escala 1-5'), ('abierta', 'Pregunta abierta')], default='likert', max_length=20, verbose_name='tipo de pregunta')),
                ('weight', models.DecimalField(decimal_places=2, default=1, help_text='Peso relativo dentro de la competencia.', max_digits=5, verbose_name='peso')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='valoracion.competency', verbose_name='competencia')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ('competency__order', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('evaluation_type', models.CharField(choices=[('lider', 'Evaluación de liderazgo'), ('operativo', 'Evaluación operativa/táctica')], max_length=20, verbose_name='tipo de evaluación')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='puntaje (sobre 5)')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='porcentaje')),
                ('level', models.CharField(choices=[('referente', 'Es un referente'), ('consolidado', 'Está consolidado'), ('desarrollo', 'En desarrollo'), ('acompanamiento', 'Requiere acompañamiento'), ('intervencion', 'Requiere intervención inmediata')], default='intervencion', max_length=20, verbose_name='semáforo')),
                ('manager_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='puntaje del jefe')),
                ('team_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='puntaje del equipo')),
                ('self_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='autoevaluación')),
                ('evaluators_total', models.PositiveIntegerField(default=0, help_text='Evaluaciones completadas que entraron.', verbose_name='calificaciones consolidadas')),
                ('evaluators_manager', models.PositiveIntegerField(default=0, verbose_name='calificaciones del jefe')),
                ('evaluators_team', models.PositiveIntegerField(default=0, verbose_name='calificaciones del equipo')),
                ('evaluators_self', models.PositiveIntegerField(default=0, verbose_name='autoevaluaciones')),
                ('competency_detail', models.JSONField(blank=True, default=list, help_text='[{code, name, label, average, percentage, level, items}]', verbose_name='detalle por competencia')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='fortalezas')),
                ('gaps', models.JSONField(blank=True, default=list, verbose_name='brechas')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='calculado el')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='valoracion.cycle', verbose_name='ciclo')),
                ('evaluatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_results', to=settings.AUTH_USER_MODEL, verbose_name='evaluado')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
                'ordering': ('-percentage',),
                'unique_together': {('cycle', 'evaluatee')},
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('description', models.TextField(verbose_name='descripción')),
                ('due_date', models.DateField(verbose_name='fecha de compromiso')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('cumplido', 'Cumplido'), ('vencido', 'Vencido')], default='pendiente', max_length=20, verbose_name='estado')),
                ('evidence_url', models.URLField(blank=True, verbose_name='evidencia')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_action_plans_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_action_plans', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='valoracion.result', verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'plan de acción',
                'verbose_name_plural': 'planes de acción',
                'ordering': ('status', 'due_date'),
            },
        ),
        migrations.CreateModel(
            name='ValuationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('results_published', models.BooleanField(default=False, help_text='Si está activo, el equipo ve sus resultados y planes de acción.', verbose_name='resultados publicados')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado el')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_settings_updates', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'configuración del módulo',
                'verbose_name_plural': 'configuración del módulo',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('value', models.PositiveSmallIntegerField(blank=True, help_text='1-5 en preguntas tipo escala.', null=True, verbose_name='valor')),
                ('text', models.TextField(blank=True, verbose_name='respuesta abierta')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='respondida el')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='valoracion.assignment', verbose_name='asignación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='valoracion.question', verbose_name='pregunta')),
            ],
            options={
                'verbose_name': 'respuesta',
                'verbose_name_plural': 'respuestas',
                'unique_together': {('assignment', 'question')},
            },
        ),
    ]
